package com.shubhi.list_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class list_object implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "LIST_OBJECT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "LIST_OBJECT_ID_SEQ", name = "LIST_OBJECT_ID_GENERATOR")
    private java.lang.Long id;

    public list_object() {
    }
    
    public list_object(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}