package com.shubhi.list_test;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class list_object implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	public java.util.List<java.lang.Long> list2 = new ArrayList<java.lang.Long>();

	public java.util.List<java.lang.Long> list1 = new ArrayList<java.lang.Long>();

	public java.util.List<java.lang.Long> getlist1() {
		return this.list1;
	}

	public java.util.List<java.lang.Long> getlist2() {
		return this.list2;
	}

	public void setList2(java.lang.Long val) {
		this.list2.add(val);
	}


	public void setList1(java.lang.Long val) {
		this.list1.add(val);
	}

	public list_object(java.util.List<java.lang.Long> list2,
			java.util.List<java.lang.Long> list1) {
		this.list2 = list2;
		this.list1 = list1;
	}

}